// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8o0VHAhn50NvSJMkZ0gWsnd9D7Z0n64o',
    appId: '1:473982143936:web:7188f55f29ccfaa71d8c25',
    messagingSenderId: '473982143936',
    projectId: 'app-chat-f9c81',
    authDomain: 'app-chat-f9c81.firebaseapp.com',
    storageBucket: 'app-chat-f9c81.firebasestorage.app',
    measurementId: 'G-E1HXF9F1LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd_O1ODHbzjZQLw9Qzpo_cBrRLsvqFHPA',
    appId: '1:473982143936:android:db1cc320300ccf4e1d8c25',
    messagingSenderId: '473982143936',
    projectId: 'app-chat-f9c81',
    storageBucket: 'app-chat-f9c81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ8OinDR6ekCQt5LncOQtxKKEB4yBBZ4g',
    appId: '1:473982143936:ios:23e7330718e268551d8c25',
    messagingSenderId: '473982143936',
    projectId: 'app-chat-f9c81',
    storageBucket: 'app-chat-f9c81.firebasestorage.app',
    iosBundleId: 'com.example.appChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ8OinDR6ekCQt5LncOQtxKKEB4yBBZ4g',
    appId: '1:473982143936:ios:23e7330718e268551d8c25',
    messagingSenderId: '473982143936',
    projectId: 'app-chat-f9c81',
    storageBucket: 'app-chat-f9c81.firebasestorage.app',
    iosBundleId: 'com.example.appChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8o0VHAhn50NvSJMkZ0gWsnd9D7Z0n64o',
    appId: '1:473982143936:web:ef2e6b669f7dfae71d8c25',
    messagingSenderId: '473982143936',
    projectId: 'app-chat-f9c81',
    authDomain: 'app-chat-f9c81.firebaseapp.com',
    storageBucket: 'app-chat-f9c81.firebasestorage.app',
    measurementId: 'G-VDMHGYJN66',
  );
}
